[package]
edition = "2021"
name = "femark"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
eyre = "0.6.8"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.4.3", default-features = false, features = ["napi4"] }
napi-derive = "2.4.1"
once_cell = "1.12.0"
pulldown-cmark = "0.9.1"
serde = {version="1.0.137", features=["derive"]}
slug = "0.1.4"
syntect = "5.0.0"
thiserror = "1.0.31"
tracing = "0.1.35"
tree-sitter = "0.20.6"
tree-sitter-bash = "0.19.0"
tree-sitter-c = "0.20.1"
tree-sitter-dockerfile = "0.1.0"
tree-sitter-go = "0.19.1"
tree-sitter-highlight = "0.20.1"
tree-sitter-html = "0.19.0"
tree-sitter-javascript = "0.20.0"
tree-sitter-json = "0.19.0"
tree-sitter-python = "0.19.1"
tree-sitter-rust = "0.20.1"
tree-sitter-toml = "0.20.0"
tree-sitter-typescript = "0.20.1"

[build-dependencies]
napi-build = "2.0.0"

[profile.release]
lto = true
