/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Renders a given markdown string to sanitized HTML
 * with formatted code blocks.
 */
export function renderMarkdown(markdown: string): string
