/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface HtmlOutput {
  toc?: string
  content: string
}
/**
 * Processes markdown to html and syntax highlights the code blocks
 * Takes in a string and returns an object containing the content HTML and the toc html
 * Input: string
 * Output: {toc: string, content: string}
 */
export function processMarkdownToHtml(input: string): HtmlOutput
