/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Processes markdown to html and syntax highlights the code blocks */
export function processMarkdownToHtml(input: string): string
